name: Test Tag creation
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    name: Tag creation
    env:
      APP_NAME: "Smartlets"
      APP_VERSION: "v1.0.0-beta"
      RUN_NUMBER: ${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create a Debug APK
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}-${{ env.RUN_NUMBER }}
          commit: dev
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
